version: '3'

services:
  db:
    image: container-registry.oracle.com/database/enterprise:19.3.0.0
    restart: always
    environment:
      ORACLE_PWD: password
    ports:
      - "1521:1521"
    healthcheck:
      test: [ "CMD", "/opt/oracle/checkDBStatus.sh"]
      interval: 2s
    networks:
      - dbNetwork

  backend:
    build: ./Backend
    command: bash -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    networks:
      - dbNetwork
      - backendNetwork
    # volumes:
    #   - ./Wallet_uwpathparallel:/code/Wallet_uwpathparallel
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SECRET_KEY=7ldnlu_gz*&vx&=4)q3#74ih@nzx*owgeu^=*katjqpbb-s1sk
      - DJANGO_SETTINGS_MODULE=uwpath_backend.dev
    #   - TNS_ADMIN=/code/Wallet_uwpathparallel


  web:
    build: ./Frontend
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backendNetwork

  dataparsing:
    build: ./DataParsing
    command: /bin/bash DataParsing/PopulateDatabase.sh
    # volumes:
    #   - .:/code
    #   - ./Wallet_uwpathparallel:/code/Wallet_uwpathparallel
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dbNetwork
    environment:
      - UWPATH_ENVIRONMENT=docker
      # - TNS_ADMIN=/code/Wallet_uwpathparallel


networks:
  dbNetwork:
    driver: bridge
  backendNetwork:
    driver: bridge
