version: 2.1
jobs:
  build:
    working_directory: /frontend
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/frontend.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/frontend.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=frontend -t frontend .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/frontend.tar frontend
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/frontend.tar
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${docker_user} -p ${docker_pass}
              docker tag frontend "uwpath/frontend:${CIRCLE_SHA1:0:8}"
              docker push "uwpath/frontend:${CIRCLE_SHA1:0:8}"
            fi
